alter table app_users add column data_version bigint not null default 0;
alter table expense_transactions add column type varchar(20) not null default 'EXPENSE';
alter table expense_transactions add column recurring boolean not null default false;
alter table expense_transactions add column wallet_payment boolean not null default false;
alter table expense_transactions add column version bigint not null default 0;
alter table expense_transactions add constraint positive_transaction_amount check(amount>0);
alter table expense_transactions add constraint transaction_type check(type in ('INCOME','EXPENSE'));
alter table budgets add column budget_month varchar(7) not null default to_char(current_date,'YYYY-MM');
-- Existing Hibernate installations can have generated names for the old uniqueness constraint.
do $$ declare c record; begin
 for c in select conname from pg_constraint where conrelid='budgets'::regclass and contype='u'
 loop execute format('alter table budgets drop constraint %I',c.conname); end loop;
end $$;
alter table budgets add constraint budget_per_month unique(user_id,category_id,budget_month);
alter table budgets add constraint positive_budget check(monthly_limit>0);
alter table budgets add constraint valid_warning check(warning_percent between 1 and 100);
alter table wallets add constraint nonnegative_wallet check(balance>=0);
create index tx_user_date on expense_transactions(user_id,occurred_at desc);
create index tx_user_category_date on expense_transactions(user_id,category_id,occurred_at);
create index budgets_user_month on budgets(user_id,budget_month);
create table event_outbox(event_id varchar(36) primary key,user_id bigint not null references app_users(id),event_type varchar(80) not null,body text not null,created_at timestamp not null,published_at timestamp);
create index pending_outbox on event_outbox(created_at) where published_at is null;
create table processed_events(consumer varchar(80) not null,event_id varchar(36) not null,processed_at timestamp not null default current_timestamp,primary key(consumer,event_id));
create table refresh_sessions(id varchar(36) primary key,user_id bigint not null references app_users(id),token_hash varchar(64) not null unique,expires_at timestamp not null,revoked boolean not null default false,created_at timestamp not null default current_timestamp);
create index sessions_user on refresh_sessions(user_id);
create table goals(id bigint generated by default as identity primary key,user_id bigint not null references app_users(id),name varchar(100) not null,target_amount numeric(14,2) not null check(target_amount>0),current_amount numeric(14,2) not null check(current_amount>=0),target_date date not null,version bigint not null default 0,created_at timestamp not null default current_timestamp);
create table detected_signals(signal_key varchar(250) primary key,user_id bigint not null references app_users(id),kind varchar(80) not null,created_at timestamp not null default current_timestamp);
create table payment_requests(user_id bigint not null references app_users(id),request_key varchar(36) not null,request_hash varchar(64) not null,response text not null,primary key(user_id,request_key));

